str = """
THIS FILE WAS GENERATED ON YUTH SEPTEMBER YWPQO.
THE QUICK BROWN FOX JUMPS OVER THE LAZY FOE.
WE DO NOT HAVE W WEEKS FOR PLANNING A STRIKE, AGAINST MOSQUITOES.
ANKIT SIR TOOK CROCS TO KILL THEM. E D PRINTER WAS SENT FOR REPAIR. ENIGMA MACHINE WAS YYYYY.
WAIT FOR NEXT CLUE TILL NEXT FORTNIGHT. CHANDRAYAN SENT THE FOLLOWING DATA.
"""
# str.toUpper()
str = str.replace(',','XNX')
str = str.replace()
print(str)
